#!/usr/bin/env python

import sys
import boto.ec2
from boto.ec2.connection import EC2Connection
import os

try:
	import json
except ImportError:
	import simplejson as json

from argparse import ArgumentParser

about = """
This script lists all security groups from the selected account.
"""

####### MAIN #######
if __name__ == '__main__':
	parser = ArgumentParser(description=about)
	parser.add_argument('--access-key', required=True, help='AWS Access Key')
	parser.add_argument('--secret-key', required=True, help='AWS Secret Key')
	parser.add_argument('--version', action='version', version='0.0.1')
	args = parser.parse_args()

	conn = EC2Connection(aws_access_key_id=args.access_key, aws_secret_access_key=args.secret_key)

	sgs = conn.get_all_security_groups()
	for sg in sgs:
		print sg.name, sg.rules
