#!/usr/bin/env python

import sys
if sys.version_info < (2, 7):
	raise Exception('Required python 2.7 or newer')

from argparse import ArgumentParser

####### MAIN #######
if __name__ == '__main__':
	parser = ArgumentParser(description='Network performance between EC2 instances')
	parser.add_argument('--access-key', required=True, help='AWS Access Key')
	parser.add_argument('--secret-key', required=True, help='AWS Secret Key')
	parser.add_argument('--version', action='version', version='0.0.1')
	args = parser.parse_args()

	print args

